=== Amatcov/GTM_dataLayer_testing/lib/validTestConfSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "baseUrl": {
            "type": "string",
            "format": "uri"
        },
        "basePath": {
            "type": "string",
            "pattern": "^/"
        },
        "dataLayerName": {
            "type": "string"
        },
        "dataLayer": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/dataLayer"
            }
        },
        "page": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/page"
            }
        }
    },
    "required": [
        "baseUrl",
        "basePath"
    ],
    "definitions": {
        "dataLayer": {
            "type": "object",
            "properties": {
                "@expect": {
                    "type": "string"
                }
            },
            "additionalProperties": {
                "allOf" : [
                    {"$ref" : "http://json-schema.org/schema#"},
                    {"$ref" : "#/definitions/rootRequired"}
                ]
            }
        },
        "page": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "pattern": "^/"
                },
                "dataLayer": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dataLayer"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "path",
                "dataLayer"
            ]
        },
        "rootRequired": {
            "type" : "object",
            "properties" : {
                "@rootRequired" : {
                    "type" : "boolean"
                }
            }
        }
    }
}

=== Amatcov/GTM_dataLayer_testing/spec/dataLayer/dataLayer.conf.json
{
    "baseUrl" : "https://www.simoahava.com",
    "basePath" : "/",
    "dataLayerName" : "dataLayer",
    "dataLayer" : [{
        "visitorLoginState" : {
            "pattern" : "^logged-(in|out)$"
        }
    },{
        "event" : {
            "pattern" : "^gtm.dom$"
        }
    },{
        "event" : {
            "pattern" : "^gtm.load$"
        }
    }],
    "page" : [{
        "path" : "/gtm-tips/10-useful-css-selectors/",
        "dataLayer" : [{
            "@expect" : "dataLayer to have basic article variables",
            "pageAttributes" : {
                "enum" : [["css-selectors", "google-tag-manager", "gtmtips"]]
            },
            "pageCategory" : {
                "enum": [["gtm-tips"]]
            },
            "pagePostType" : {
                "pattern" : "^post$"
            },
            "pagePostType2" : {
                "pattern": "^single-post$"
            },
            "postCountOnPage" : {
                "type" : "number"
            },
            "postCountTotal" : {
                "type" : "number"
            }
        },{
            "@expect" : "dataLayer to have article impressions",
            "event" : {
                "pattern": "^impressionsPushed$"
            },
            "ecommerce" : {
                "type" : "object",
                "properties" : {
                    "impressions": {
                        "$ref" : "/enhancedEcommerceSchema.json#/definitions/impressions"
                    }
                },
                "required" : ["impressions"]
            }
        },{
            "@expect" : "dataLayer to have clientId",
            "event" : {
                "pattern" : "^trackerReady$"
            },
            "cid" : {
                "type" : "string",
                "pattern" : "[0-9]+\\.[0-9]+"
            }
        },{
            "@expect" : "dataLayer to have product detail view",
            "ecommerce" : {
                "type" : "object",
                "properties" : {
                    "detail" : {
                        "$ref" : "/enhancedEcommerceSchema.json#/definitions/detail"
                    }
                },
                "required" : ["detail"]
            }
        }]
    }]
}
